export const ApiContextType = {
  START_FETCH_SPEND: "START_FETCH_SPEND",
  STOP_FETCH_SPEND: "STOP_FETCH_SPEND",
  START_ADD_SPEND: "START_ADD_SPEND",
  STOP_ADD_SPEND: "STOP_ADD_SPEND",
  SET_CATEGORIES: "SET_CATEGORIES",
  START_FETCH_DASHBOARD: "START_FETCH_DASHBOARD",
  STOP_FETCH_DASHBOARD: "STOP_FETCH_DASHBOARD",
};
